version: "3"
services:
  servicea:
    build:
      context: ./servicea
      dockerfile: Dockerfile
    image: kjh99723/servicea:latest
    container_name: servicea
    ports:
      - 8098:8098
    

  serviceb:
    build:
      context: ./serviceb
      dockerfile: Dockerfile
    image: kjh99723/serviceb:latest
    container_name: serviceb
    ports:
      - 8099:8099
